package com.ideashower.readitlater.h;

import android.os.Build;
import com.ideashower.readitlater.util.j;
import org.apache.a.c.k;

public class a
{
  public static final b A;
  public static final b B;
  public static final b C;
  public static final b D;
  public static final b E;
  public static final d F;
  public static final b G;
  public static final b H;
  public static final b I;
  public static final d J;
  public static final b K;
  public static final b L;
  public static final b M;
  public static final e N;
  public static final e O;
  public static final d P;
  public static final d Q;
  public static final e R;
  public static final e S;
  public static final d T;
  public static final d U;
  public static final b V;
  public static final b W;
  public static final d X;
  public static final b Y;
  public static final d Z;
  public static final h a = new h("username", g.a, null);
  public static final h aA;
  public static final h aB;
  public static final d aC;
  public static final b aD;
  public static final h aE;
  public static final h aF;
  public static final b aG;
  public static final d aH;
  public static final b aI;
  public static final d aJ;
  public static final d aK;
  public static final d aL;
  public static final d aM;
  public static final e aN;
  public static final b aO;
  public static final b aP;
  public static final d aQ;
  public static final b aR;
  public static final b aS;
  public static final h aT;
  public static final b aU;
  public static final b aV;
  public static final b aW;
  public static final b aX;
  public static final e aY;
  public static final b aZ;
  public static final e aa;
  public static final d ab;
  public static final e ac;
  public static final e ad;
  public static final d ae;
  public static final h af;
  public static final e ag;
  @Deprecated
  public static final b ah;
  public static final d ai;
  public static final b aj;
  public static final d ak;
  public static final b al;
  public static final d am;
  public static final e an;
  public static final d ao;
  public static final d ap;
  public static final b aq;
  public static final b ar;
  public static final c as;
  public static final h at;
  public static final b au;
  public static final d av;
  public static final b aw;
  public static final b ax;
  public static final b ay;
  public static final b az;
  @Deprecated
  public static final h b = new h("password", g.a, null);
  public static final b bA;
  public static final b bB;
  public static final d bC;
  public static final b bD;
  public static final b bE;
  public static final d bF;
  public static final d bG;
  public static final b bH;
  public static final d bI;
  public static final b bJ;
  public static final b bK;
  public static final b bL;
  public static final b bM;
  public static final b bN;
  public static final b bO;
  public static final b bP;
  public static final d bQ;
  public static final d bR;
  public static final b bS;
  public static final d bT;
  public static final d bU;
  public static final b bV;
  public static final b bW;
  public static final b bX;
  public static final b bY;
  public static final b bZ;
  public static final d ba;
  public static final b bb;
  public static final d bc;
  public static final d bd;
  public static final h be;
  public static final b bf;
  public static final b bg;
  public static final b bh;
  public static final d bi;
  public static final b bj;
  public static final h bk;
  public static final b bl;
  public static final b bm;
  public static final b bn;
  public static final d bo;
  public static final e bp;
  public static final b bq;
  public static final d br;
  public static final h bs;
  public static final h bt;
  public static final h bu;
  public static final h bv;
  public static final h bw;
  public static final h bx;
  public static final h by;
  public static final b bz;
  public static final h c = new h("scrollbarHash", g.a, null);
  public static final h ca;
  public static final h cb;
  public static final h cc;
  public static final b cd;
  public static final h ce;
  public static final d cf;
  public static final h cg;
  public static final b ch;
  public static final b ci;
  public static final b cj;
  public static final b ck;
  public static final h cl;
  public static final b cm;
  public static final b cn;
  public static final b co;
  public static final b cp;
  public static final b cq;
  public static final d cr;
  public static final d cs;
  public static final b ct;
  public static final h cu;
  public static final h cv;
  public static final h d = new h("c2dmTempId", g.a, null);
  public static final h e = new h("uid", g.a, null);
  public static final d f = new d("fid", g.a, null);
  public static final b g = new b("userHasSetAvatar", g.a, null);
  public static final b h = new b("userHasSavedFromAndroid", g.a, null);
  public static final h i = new h("firstName", g.a, null);
  public static final h j = new h("lastName", g.a, null);
  public static final h k = new h("email", g.a, null);
  public static final h l = new h("emailAliases", g.a, null);
  public static final d m = new d("logmethod", 0, g.a, null);
  public static final b n = new b("promptpass", false, g.a, null);
  public static final h o = new h("googleaccount", null, g.a, null);
  public static final b p = new b("googleconnected", false, g.a, null);
  public static final b q = new b("invalidcred", false, g.b, null);
  public static final b r = new b("oldamzky", false, g.a, null);
  public static final d s = new d("premium_status", 0, g.a, null);
  public static final h t = new h("pending_gift", g.a, null);
  public static final b u = new b("cleargacct", g.b, null);
  public static final b v = new b("gsautoenable", true, g.b, null);
  public static final b w = new b("isNewUser", g.a, null);
  public static final h x = new h("guid", g.b, null);
  public static final b y = new b("shownGetStarted", g.a, null);
  public static final b z = new b("autoOpenBestView", true, g.a, null);
  
  static
  {
    A = new b("scrollbar", true, g.a, null);
    B = new b("downloadAuto", true, g.a, null);
    C = new b("downloadText", true, g.a, null);
    D = new b("downloadWeb", true, g.a, null);
    E = new b("autoSync", true, g.a, null);
    F = new d("queueSort", 0, g.a, null);
    G = new b("excludeTagged", false, g.a, null);
    H = new b("autoOnlyWifi", false, g.a, null);
    I = new b("userAgentMobile", false, g.a, null);
    J = new d("backgroundSyncingValue", 2, g.a, null);
    K = new b("scrollByVolume", g.a, null);
    L = new b("useSdCard", true, g.a, null);
    M = new b("sdCardSetup", g.a, null);
    N = new e("cacheLimit", g.a, null);
    O = new e("cacheLimitTemp", g.a, null);
    P = new d("cacheSort", 0, g.a, null);
    Q = new d("cacheSortTemp", 0, g.a, null);
    R = new e("cacheUsed", g.a, null);
    S = new e("dbSize", g.a, null);
    T = new d("assetMigration", 0, g.a, null);
    U = new d("assetMigrationId", g.a, null);
    V = new b("cacheDLock", g.a, null);
    W = new b("firstLoad", true, g.b, null);
    X = new d("previousAppVersion", g.b, null);
    Y = new b("firstLogin", true, g.b, null);
    Z = new d("orientation", 4, g.b, null);
    aa = new e("whenLastPaused", g.b, null);
    ab = new d("unique_id", 10000, g.a, null);
    ac = new e("since", g.a, null);
    ad = new e("since_m", g.a, null);
    ae = new d("path_inc", 1, g.b, null);
    af = new h("mobileAgentString", g.b, null);
    ag = new e("lastNewGet", g.a, null);
    ah = new b("syncQueriesPending", g.a, null);
    ai = new d("syncQueriesPendingLevel", 0, g.a, null);
    aj = new b("allowLaunchFix", true, g.b, null);
    ak = new d("abTestNewAccountEmail", g.b, null);
    al = new b("pien", g.a, null);
    am = new d("downloadingPausedCount", g.a, null);
    an = new e("downloadingPausedTimeUpdated", g.a, null);
    ao = new d("readerViewType", 1, g.a, null);
    ap = new d("articleFontSize", com.ideashower.readitlater.a.g.b(2131361792), g.a, null);
    aq = new b("articleSerif", true, g.a, null);
    ar = new b("articleJustify", g.a, null);
    as = new c("articleTTSSpeed", 1.0F, g.a, null);
    at = new h("articleTTSLang", g.a, null);
    au = new b("articleTTSExplained", g.a, null);
    av = new d("appTheme", 0, g.a, null);
    aw = new b("appThemeDark", g.a, null);
    ax = new b("appThemeUseBlack", k.c(Build.MANUFACTURER, "Samsung"), g.a, null);
    ay = new b("pageFlipping", true, g.a, null);
    az = new b("autoFullscreen", true, g.a, null);
    aA = new h("ttsEngine", g.a, null);
    aB = new h("ttsEnginesKnown", g.b, null);
    int i1;
    if (j.c())
    {
      i1 = 0;
      aC = new d("listMode", i1, g.a, null);
      aD = new b("hasSeenBulkEditTutorial", g.b, null);
      aE = new h("osBuildKey", g.b, null);
      aF = new h("pendingCustomSubscription", g.a, null);
      aG = new b("hasFetched", g.a, null);
      aH = new d("firstChunkSize", g.a, null);
      aI = new b("firstChunkComplete", g.a, null);
      aJ = new d("fetchChunkSize", g.a, null);
      aK = new d("fetchChunksDone", g.a, null);
      aL = new d("fetchTotalItems", g.a, null);
      aM = new d("fetchTotalChunks", g.a, null);
      aN = new e("fetchStartTime", g.a, null);
      aO = new b("needsToStartFetching", g.a, null);
      aP = new b("fetchChunkReceived", false, g.a, null);
      aQ = new d("fetchProgress", g.a, null);
      aR = new b("firstSyncComplete", g.a, null);
      aS = new b("upgradedToPocket", g.b, null);
      aT = new h("bv", g.b, null);
      aU = new b("hasSyncedForSharing", g.a, null);
      aV = new b("hasSyncedForTweets", g.a, null);
      aW = new b("hasSyncedForRediscovery", g.a, null);
      aX = new b("showUpdateFlow", g.b, null);
      aY = new e("sid", g.b, null);
      aZ = new b("reregisterC2DM", g.a, null);
      ba = new d("lastClipUrlHash", g.a, null);
      if ((!com.ideashower.readitlater.util.a.l()) || (!j.c())) {
        break label3142;
      }
    }
    label3142:
    for (boolean bool = false;; bool = true)
    {
      bb = new b("enableRotationLock", bool, g.a, null);
      bc = new d("screenWidthShort", g.b, null);
      bd = new d("screenWidthLong", g.b, null);
      be = new h("abTests", g.b, null);
      bf = new b("pvab_", false, g.b, null);
      bg = new b("showUpdatedScreen", g.b, null);
      bh = new b("resetUID", g.a, null);
      bi = new d("photoEditorStatus", g.a, null);
      bj = new b("notify", true, g.a, null);
      bk = new h("notifySound", null, g.a, null);
      bl = new b("notifyLights", true, g.a, null);
      bm = new b("hasPromptedForName", g.a, null);
      bn = new b("add_overlay", true, g.a, null);
      bo = new d("lastLoginRuleCheck", g.a, null);
      bp = new e("to_", 0L, g.a, null);
      bq = new b("umsg_", false, g.a, null);
      br = new d("avatar_file_inc_", 1, g.a, null);
      bs = new h("avsfbd", null, g.a, null);
      bt = new h("avsfba", null, g.a, null);
      bu = new h("avsts", null, g.a, null);
      bv = new h("avst", null, g.a, null);
      bw = new h("twappauthtk", null, g.b, null);
      bx = new h("lastShareVia", g.a, null);
      by = new h("lastShareArticleVia", g.a, null);
      bz = new b("hasPromptAvatarEditor", false, g.a, null);
      bA = new b("wawr", false, g.a, null);
      bB = new b("hasNotedUnconfirmedEmail_", g.a, null);
      bC = new d("lastGsfDemoSuccess", g.a, null);
      bD = new b("gsfActive", false, g.a, null);
      bE = new b("gsfDemoBased", false, g.a, null);
      bF = new d("gsffcss", g.a, null);
      bG = new d("gsfSuccessfulAppId", g.a, null);
      bH = new b("gsfReturnedToPocket", g.a, null);
      bI = new d("gsfevc_", g.a, null);
      bJ = new b("gsf_show_add_more_footer", true, g.a, null);
      bK = new b("gsf_has_visited_reader", false, g.a, null);
      bL = new b("gsf_has_saved_video", false, g.a, null);
      bM = new b("gsf_has_saved_article", false, g.a, null);
      bN = new b("gsf_has_sent_email_from_list", false, g.a, null);
      bO = new b("gsf_counting_saves", false, g.a, null);
      bP = new b("gsf_watch_need_help", g.a, null);
      bQ = new d("gsf_last_save_count", g.a, null);
      bR = new d("gsf_might_need_help", g.a, null);
      bS = new b("gsf_show_skip", false, g.a, null);
      bT = new d("saves", g.a, null);
      bU = new d("show_archived_tooltip", 0, g.a, null);
      bV = new b("reader_guide_article", g.a, null);
      bW = new b("reader_guide_web", g.a, null);
      bX = new b("reader_guide_actions", g.a, null);
      bY = new b("webview_disabled_zoom_tip_toast", g.a, null);
      bZ = new b("ty_error_prompt", g.a, null);
      ca = new h("send_parse_crash", null, g.a, null);
      cb = new h("send_parse_response", null, g.a, null);
      cc = new h("send_parse_request", null, g.a, null);
      cd = new b("seenHighlights", false, g.a, null);
      ce = new h("groups", null, g.a, null);
      cf = new d("inbox_count_viewed", 0, g.a, null);
      cg = new h("ppactivation", null, g.a, null);
      ch = new b("ablg_gauth", false, g.b, null);
      ci = new b("ablg_lmore", false, g.b, null);
      cj = new b("ablg_premup_st", false, g.a, null);
      ck = new b("ablg_premup_b", false, g.a, null);
      cl = new h("rffrgp", g.b, null);
      cm = new b("dcfig_enabled", false, g.b, null);
      cn = new b("dcfig_google_auth", true, g.b, null);
      co = new b("dcfig_lmore", true, g.b, null);
      cp = new b("dcfig_uspselltags", true, g.b, null);
      cq = new b("dcfig_uspsellsearch", true, g.b, null);
      cr = new d("dcfig_ps", 0, g.a, null);
      cs = new d("dcfig_saction", 0, g.a, null);
      ct = new b("dia_cl", false, g.a, null);
      cu = new h("spoofedLocaleLang", g.b, null);
      cv = new h("spoofedLocaleCountry", g.b, null);
      return;
      i1 = 1;
      break;
    }
  }
  
  public static void a()
  {
    i.b().a(e, i.a(new h("userUID", g.a, null))).a("userUID", g.a).a(B, i.a(new b("downloadAutoPick", B.a, g.a, null))).a("downloadAutoPick", g.a).a(H, i.a(new b("autoOnlyOnWifi", H.a, g.a, null))).a("autoOnlyOnWifi", g.a).a(I, i.a(new b("mobileAgent", I.a, g.a, null))).a("mobileAgent", g.a).a("articleImages", g.a).a("leftyScrollbar", g.a).a("sortReading", g.a).a("sortCurrent", g.a).a("sortRead", g.a).a("sortRead", g.a).a("list_size", g.a).a("faviconFailedHostReset", g.a).a("filterReading", g.a).a("filterRead", g.a).a("filterCurrent", g.a).a("filterTagDir", g.a).a("Time", g.a).a("lastUpgradeTo", g.a).a("lastUpdateScreenShownFor", g.a).a(ac).a(Z).a(aG, false).a(aO, true).a(y, true).a(aX, true).a(aS, true).a();
  }
}


/* Location:              /Users/amaurremi/uw/stringoid/static-dynamic-comparison/apps/pocket/com.ideashower.readitlater.pro-568-dex2jar.jar!/com/ideashower/readitlater/h/a.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */