package com.venticake.retrica.engine.a;

import android.annotation.SuppressLint;
import android.opengl.GLES20;
import com.venticake.retrica.util.a;
import java.nio.FloatBuffer;

public class j
  extends f
{
  private static final byte[] u = { 98, -54, 1, -109, -46, -127, 30, -6, -70, 122, 14, -31, 100, -95, 64, 61, -110, 44, 73, 3, -41, 5, 32, -31, 100, -30, -97, 65, -116, 55, -50, -26, -103, -101, -50, -6, 5, 54, 32, 33, -22, 113, 47, -111, -58, -127, -64, 62, -74, -73, -51, -60, -84, -30, 98, 73, 30, -68, -47, -119, -66, -72, -85, -21, -82, 67, 119, 112, 23, -24, -85, -11, 77, 127, 15, 30, 63, -96, -84, 11, 38, -34, 9, -111, 8, 126, 119, -62, 102, 7, 80, -15, -78, 24, 66, 85, 112, 69, 34, 28, 42, 59, -95, 74, 36, -54, 21, 105, -82, -65, 110, 12, 93, 72, -126, 34, 28, -123, -68, -74, -35, 87, -87, 111, 11, 123, -28, -60, -87, 42, 72, -75, 126, -24, -57, -64, -82, 60, 96, -24, -53, -111, 47, -2, -27, -98, -30, 127, -59, 42, 77, -64, -29, -91, -17, -9, -88, -62, 49, 56, -16, -109, -90, -97, -91, 52, -42, 68, 105, 21, 16, -45, 95, -112, -49, -5, -25, -69, 60, 10, -23, 77, 87, 67, 44, 68, 24, -45, 101, 108, 88, -37, 103, 114, -124, -87, -55, -63, 99, -48, -60, 115, -5, -19, 29, 37, -101, 81, 107, 56, 21, -128, 111, 121, 94, 79, -22, -45, -119, -15, 95, 19, 25, 77, -29, 125, 63, 54, 69, 109, -46, -85, 108, 44, 67, -23, -106, 46, 72, 78, 103, -6, -79, -66, -37, 27, -8, -42, -94, 121, 51, -37, 48, 127, 15, 120, 115, 88, -28, -112, -108, -81, -26, 55, -110, 8, -70, -119, 13, -29, -53, -31, 110, 124, 24, 84, 37, -78, 60, -5, -87, 66, -105, -127, -88, 57, 112, 70, -13, -32, -39, -104, -102, -65, -91, -79, 31, 74, -37, -52, -82, -75, 17, -70, 72, 100, -80, -79, 18, -48, -48, 124, -114, 64, -60, -48, -84, 15, -52, 123 };
  private static String v = null;
  private static final byte[] w;
  private static String x = null;
  public int a;
  public int b;
  public int g = -1;
  private FloatBuffer h;
  private int i;
  private int j;
  private int k;
  private int l;
  private int m;
  private float n = 0.4F;
  private float o = 0.5F;
  private float p = 0.5F;
  private float q = 0.003125F;
  private float r = 1.0F;
  private float s = 0.0F;
  private boolean t = false;
  
  static
  {
    byte[] arrayOfByte = new byte['Ӱ'];
    arrayOfByte[0] = 76;
    arrayOfByte[1] = -111;
    arrayOfByte[2] = 25;
    arrayOfByte[3] = 42;
    arrayOfByte[4] = -21;
    arrayOfByte[5] = -69;
    arrayOfByte[6] = -103;
    arrayOfByte[7] = 91;
    arrayOfByte[8] = 57;
    arrayOfByte[9] = 84;
    arrayOfByte[10] = 88;
    arrayOfByte[11] = -16;
    arrayOfByte[12] = -89;
    arrayOfByte[13] = 58;
    arrayOfByte[14] = 21;
    arrayOfByte[15] = 34;
    arrayOfByte[16] = -90;
    arrayOfByte[17] = -80;
    arrayOfByte[18] = 77;
    arrayOfByte[19] = 118;
    arrayOfByte[20] = -114;
    arrayOfByte[21] = 48;
    arrayOfByte[22] = -76;
    arrayOfByte[23] = 5;
    arrayOfByte[24] = 115;
    arrayOfByte[25] = -10;
    arrayOfByte[26] = 55;
    arrayOfByte[27] = 122;
    arrayOfByte[28] = -120;
    arrayOfByte[29] = 54;
    arrayOfByte[30] = 27;
    arrayOfByte[31] = -121;
    arrayOfByte[32] = 126;
    arrayOfByte[33] = 8;
    arrayOfByte[34] = 81;
    arrayOfByte[35] = -24;
    arrayOfByte[36] = -92;
    arrayOfByte[37] = 50;
    arrayOfByte[38] = -104;
    arrayOfByte[39] = -72;
    arrayOfByte[40] = 39;
    arrayOfByte[41] = 68;
    arrayOfByte[42] = 95;
    arrayOfByte[44] = 99;
    arrayOfByte[45] = -93;
    arrayOfByte[46] = 116;
    arrayOfByte[47] = -58;
    arrayOfByte[48] = -121;
    arrayOfByte[49] = 21;
    arrayOfByte[50] = -67;
    arrayOfByte[51] = 63;
    arrayOfByte[52] = Byte.MIN_VALUE;
    arrayOfByte[53] = 31;
    arrayOfByte[54] = -87;
    arrayOfByte[55] = 122;
    arrayOfByte[56] = 67;
    arrayOfByte[57] = 87;
    arrayOfByte[58] = 39;
    arrayOfByte[59] = 50;
    arrayOfByte[60] = 96;
    arrayOfByte[61] = 4;
    arrayOfByte[62] = -98;
    arrayOfByte[63] = 75;
    arrayOfByte[64] = -37;
    arrayOfByte[65] = -10;
    arrayOfByte[66] = 53;
    arrayOfByte[67] = -14;
    arrayOfByte[68] = -88;
    arrayOfByte[69] = 1;
    arrayOfByte[70] = 14;
    arrayOfByte[71] = 44;
    arrayOfByte[72] = 45;
    arrayOfByte[73] = 14;
    arrayOfByte[74] = 6;
    arrayOfByte[75] = -56;
    arrayOfByte[76] = 111;
    arrayOfByte[77] = 37;
    arrayOfByte[78] = 40;
    arrayOfByte[79] = -87;
    arrayOfByte[80] = -16;
    arrayOfByte[81] = -108;
    arrayOfByte[82] = 78;
    arrayOfByte[83] = -56;
    arrayOfByte[84] = -49;
    arrayOfByte[85] = 93;
    arrayOfByte[86] = -11;
    arrayOfByte[87] = -42;
    arrayOfByte[88] = Byte.MAX_VALUE;
    arrayOfByte[89] = -84;
    arrayOfByte[90] = -28;
    arrayOfByte[91] = -12;
    arrayOfByte[92] = -80;
    arrayOfByte[93] = 53;
    arrayOfByte[94] = 122;
    arrayOfByte[95] = -4;
    arrayOfByte[96] = -24;
    arrayOfByte[97] = 69;
    arrayOfByte[98] = -66;
    arrayOfByte[99] = 6;
    arrayOfByte[100] = -32;
    arrayOfByte[101] = 60;
    arrayOfByte[102] = 58;
    arrayOfByte[103] = -30;
    arrayOfByte[104] = 49;
    arrayOfByte[105] = 7;
    arrayOfByte[106] = 79;
    arrayOfByte[107] = -116;
    arrayOfByte[108] = -6;
    arrayOfByte[109] = -64;
    arrayOfByte[110] = -125;
    arrayOfByte[111] = 83;
    arrayOfByte[112] = 9;
    arrayOfByte[113] = 119;
    arrayOfByte[114] = -108;
    arrayOfByte[115] = 87;
    arrayOfByte[116] = -88;
    arrayOfByte[117] = 98;
    arrayOfByte[118] = 116;
    arrayOfByte[119] = 71;
    arrayOfByte[120] = -57;
    arrayOfByte[121] = -117;
    arrayOfByte[122] = -7;
    arrayOfByte[123] = 7;
    arrayOfByte[124] = -85;
    arrayOfByte[125] = 69;
    arrayOfByte[126] = -86;
    arrayOfByte[127] = 16;
    arrayOfByte[''] = -67;
    arrayOfByte[''] = 106;
    arrayOfByte[''] = 108;
    arrayOfByte[''] = -72;
    arrayOfByte[''] = -77;
    arrayOfByte[''] = 98;
    arrayOfByte[''] = 56;
    arrayOfByte[''] = 98;
    arrayOfByte[''] = -122;
    arrayOfByte[''] = 24;
    arrayOfByte[''] = -65;
    arrayOfByte[''] = -38;
    arrayOfByte[''] = -116;
    arrayOfByte[''] = 84;
    arrayOfByte[''] = -89;
    arrayOfByte[''] = 15;
    arrayOfByte[''] = -119;
    arrayOfByte[''] = -83;
    arrayOfByte[''] = -83;
    arrayOfByte[''] = 99;
    arrayOfByte[''] = -113;
    arrayOfByte[''] = 47;
    arrayOfByte[''] = -120;
    arrayOfByte[''] = -2;
    arrayOfByte[''] = 102;
    arrayOfByte[''] = -24;
    arrayOfByte[''] = 119;
    arrayOfByte[''] = -79;
    arrayOfByte[''] = 70;
    arrayOfByte[''] = 117;
    arrayOfByte[''] = -13;
    arrayOfByte[''] = 51;
    arrayOfByte[' '] = -11;
    arrayOfByte['¡'] = 124;
    arrayOfByte['¢'] = -59;
    arrayOfByte['£'] = 95;
    arrayOfByte['¤'] = 122;
    arrayOfByte['¥'] = -47;
    arrayOfByte['¦'] = -118;
    arrayOfByte['§'] = -80;
    arrayOfByte['¨'] = 105;
    arrayOfByte['©'] = 30;
    arrayOfByte['ª'] = 90;
    arrayOfByte['«'] = 120;
    arrayOfByte['¬'] = 5;
    arrayOfByte['­'] = 125;
    arrayOfByte['®'] = -120;
    arrayOfByte['¯'] = -54;
    arrayOfByte['°'] = -12;
    arrayOfByte['±'] = -106;
    arrayOfByte['²'] = 61;
    arrayOfByte['³'] = 106;
    arrayOfByte['´'] = -112;
    arrayOfByte['µ'] = 68;
    arrayOfByte['¶'] = -67;
    arrayOfByte['·'] = 74;
    arrayOfByte['¸'] = 48;
    arrayOfByte['¹'] = 40;
    arrayOfByte['º'] = 21;
    arrayOfByte['»'] = 62;
    arrayOfByte['¼'] = -71;
    arrayOfByte['½'] = 33;
    arrayOfByte['¾'] = -53;
    arrayOfByte['¿'] = -106;
    arrayOfByte['À'] = 43;
    arrayOfByte['Á'] = -63;
    arrayOfByte['Â'] = -38;
    arrayOfByte['Ã'] = -1;
    arrayOfByte['Ä'] = 2;
    arrayOfByte['Å'] = 124;
    arrayOfByte['Æ'] = 122;
    arrayOfByte['Ç'] = 87;
    arrayOfByte['È'] = -37;
    arrayOfByte['É'] = -92;
    arrayOfByte['Ê'] = 59;
    arrayOfByte['Ë'] = 111;
    arrayOfByte['Ì'] = 104;
    arrayOfByte['Í'] = -82;
    arrayOfByte['Î'] = 37;
    arrayOfByte['Ï'] = -38;
    arrayOfByte['Ð'] = -11;
    arrayOfByte['Ñ'] = 56;
    arrayOfByte['Ò'] = 123;
    arrayOfByte['Ó'] = 22;
    arrayOfByte['Ô'] = -67;
    arrayOfByte['Õ'] = -91;
    arrayOfByte['Ö'] = 82;
    arrayOfByte['×'] = 14;
    arrayOfByte['Ø'] = -43;
    arrayOfByte['Ù'] = 46;
    arrayOfByte['Ú'] = 19;
    arrayOfByte['Û'] = -111;
    arrayOfByte['Ü'] = -28;
    arrayOfByte['Ý'] = 33;
    arrayOfByte['Þ'] = 73;
    arrayOfByte['ß'] = 5;
    arrayOfByte['à'] = 33;
    arrayOfByte['á'] = 96;
    arrayOfByte['â'] = -67;
    arrayOfByte['ã'] = 7;
    arrayOfByte['ä'] = 13;
    arrayOfByte['å'] = 42;
    arrayOfByte['æ'] = -14;
    arrayOfByte['ç'] = 123;
    arrayOfByte['è'] = -48;
    arrayOfByte['é'] = 41;
    arrayOfByte['ê'] = -32;
    arrayOfByte['ë'] = 74;
    arrayOfByte['ì'] = 16;
    arrayOfByte['í'] = 67;
    arrayOfByte['î'] = -114;
    arrayOfByte['ï'] = -45;
    arrayOfByte['ð'] = -116;
    arrayOfByte['ñ'] = -72;
    arrayOfByte['ò'] = 47;
    arrayOfByte['ó'] = -25;
    arrayOfByte['ô'] = -74;
    arrayOfByte['õ'] = -119;
    arrayOfByte['ö'] = 119;
    arrayOfByte['÷'] = -74;
    arrayOfByte['ø'] = 59;
    arrayOfByte['ù'] = 40;
    arrayOfByte['ú'] = 28;
    arrayOfByte['û'] = -17;
    arrayOfByte['ü'] = 60;
    arrayOfByte['ý'] = -44;
    arrayOfByte['þ'] = -22;
    arrayOfByte['ÿ'] = 84;
    arrayOfByte['Ā'] = 90;
    arrayOfByte['ā'] = 91;
    arrayOfByte['Ă'] = 105;
    arrayOfByte['ă'] = 26;
    arrayOfByte['Ą'] = 33;
    arrayOfByte['ą'] = 56;
    arrayOfByte['Ć'] = 64;
    arrayOfByte['ć'] = -40;
    arrayOfByte['Ĉ'] = -80;
    arrayOfByte['ĉ'] = Byte.MAX_VALUE;
    arrayOfByte['Ċ'] = 70;
    arrayOfByte['ċ'] = 27;
    arrayOfByte['Č'] = -55;
    arrayOfByte['č'] = -114;
    arrayOfByte['Ď'] = -105;
    arrayOfByte['ď'] = -57;
    arrayOfByte['Đ'] = -59;
    arrayOfByte['đ'] = 85;
    arrayOfByte['Ē'] = -114;
    arrayOfByte['ē'] = -115;
    arrayOfByte['Ĕ'] = 4;
    arrayOfByte['ĕ'] = 40;
    arrayOfByte['Ė'] = 18;
    arrayOfByte['ė'] = -22;
    arrayOfByte['Ę'] = 66;
    arrayOfByte['ę'] = -85;
    arrayOfByte['Ě'] = 38;
    arrayOfByte['ě'] = -12;
    arrayOfByte['Ĝ'] = -93;
    arrayOfByte['ĝ'] = -55;
    arrayOfByte['Ğ'] = -104;
    arrayOfByte['ğ'] = 77;
    arrayOfByte['Ġ'] = -73;
    arrayOfByte['ġ'] = -124;
    arrayOfByte['Ģ'] = 78;
    arrayOfByte['ģ'] = -85;
    arrayOfByte['Ĥ'] = 46;
    arrayOfByte['ĥ'] = 61;
    arrayOfByte['Ħ'] = -97;
    arrayOfByte['ħ'] = -44;
    arrayOfByte['Ĩ'] = 90;
    arrayOfByte['ĩ'] = 105;
    arrayOfByte['Ī'] = 76;
    arrayOfByte['ī'] = 79;
    arrayOfByte['Ĭ'] = -18;
    arrayOfByte['ĭ'] = 12;
    arrayOfByte['Į'] = 21;
    arrayOfByte['į'] = -99;
    arrayOfByte['İ'] = -45;
    arrayOfByte['ı'] = -36;
    arrayOfByte['Ĳ'] = -36;
    arrayOfByte['ĳ'] = -12;
    arrayOfByte['Ĵ'] = -114;
    arrayOfByte['ĵ'] = -124;
    arrayOfByte['Ķ'] = -47;
    arrayOfByte['ķ'] = -15;
    arrayOfByte['ĸ'] = -119;
    arrayOfByte['Ĺ'] = 7;
    arrayOfByte['ĺ'] = -124;
    arrayOfByte['Ļ'] = 43;
    arrayOfByte['ļ'] = 120;
    arrayOfByte['Ľ'] = 75;
    arrayOfByte['ľ'] = 105;
    arrayOfByte['Ŀ'] = -2;
    arrayOfByte['ŀ'] = 32;
    arrayOfByte['Ł'] = -55;
    arrayOfByte['ł'] = Byte.MAX_VALUE;
    arrayOfByte['Ń'] = 62;
    arrayOfByte['ń'] = -98;
    arrayOfByte['Ņ'] = -48;
    arrayOfByte['ņ'] = 53;
    arrayOfByte['Ň'] = -75;
    arrayOfByte['ň'] = -5;
    arrayOfByte['ŉ'] = 7;
    arrayOfByte['Ŋ'] = -10;
    arrayOfByte['ŋ'] = -31;
    arrayOfByte['Ō'] = 40;
    arrayOfByte['ō'] = -46;
    arrayOfByte['ŏ'] = -104;
    arrayOfByte['Ő'] = -119;
    arrayOfByte['ő'] = -75;
    arrayOfByte['Œ'] = -16;
    arrayOfByte['œ'] = 120;
    arrayOfByte['Ŕ'] = 45;
    arrayOfByte['ŕ'] = 114;
    arrayOfByte['Ŗ'] = -102;
    arrayOfByte['ŗ'] = 85;
    arrayOfByte['Ř'] = 87;
    arrayOfByte['ř'] = 34;
    arrayOfByte['Ś'] = 32;
    arrayOfByte['ś'] = 118;
    arrayOfByte['Ŝ'] = 119;
    arrayOfByte['ŝ'] = 11;
    arrayOfByte['Ş'] = 110;
    arrayOfByte['ş'] = 26;
    arrayOfByte['Š'] = -21;
    arrayOfByte['š'] = -4;
    arrayOfByte['Ţ'] = -108;
    arrayOfByte['ţ'] = -66;
    arrayOfByte['Ť'] = 112;
    arrayOfByte['ť'] = -81;
    arrayOfByte['Ŧ'] = 50;
    arrayOfByte['ŧ'] = -107;
    arrayOfByte['Ũ'] = 47;
    arrayOfByte['ũ'] = 35;
    arrayOfByte['Ū'] = 50;
    arrayOfByte['ū'] = 102;
    arrayOfByte['Ŭ'] = 62;
    arrayOfByte['ŭ'] = 51;
    arrayOfByte['Ů'] = -126;
    arrayOfByte['ů'] = 126;
    arrayOfByte['Ű'] = 2;
    arrayOfByte['ű'] = -34;
    arrayOfByte['Ų'] = 84;
    arrayOfByte['ų'] = -123;
    arrayOfByte['Ŵ'] = 38;
    arrayOfByte['ŵ'] = 118;
    arrayOfByte['Ŷ'] = -83;
    arrayOfByte['ŷ'] = 85;
    arrayOfByte['Ÿ'] = 51;
    arrayOfByte['Ź'] = 42;
    arrayOfByte['ź'] = -25;
    arrayOfByte['Ż'] = 106;
    arrayOfByte['ż'] = -51;
    arrayOfByte['Ž'] = 78;
    arrayOfByte['ž'] = 85;
    arrayOfByte['ſ'] = -40;
    arrayOfByte['ƀ'] = 23;
    arrayOfByte['Ɓ'] = -65;
    arrayOfByte['Ƃ'] = -84;
    arrayOfByte['ƃ'] = -27;
    arrayOfByte['Ƅ'] = 94;
    arrayOfByte['ƅ'] = -19;
    arrayOfByte['Ɔ'] = -74;
    arrayOfByte['Ƈ'] = 37;
    arrayOfByte['ƈ'] = 10;
    arrayOfByte['Ɖ'] = -87;
    arrayOfByte['Ɗ'] = -99;
    arrayOfByte['Ƌ'] = 21;
    arrayOfByte['ƌ'] = 100;
    arrayOfByte['ƍ'] = 106;
    arrayOfByte['Ǝ'] = -42;
    arrayOfByte['Ə'] = 70;
    arrayOfByte['Ɛ'] = -118;
    arrayOfByte['Ƒ'] = 65;
    arrayOfByte['ƒ'] = -66;
    arrayOfByte['Ɠ'] = -43;
    arrayOfByte['Ɣ'] = -88;
    arrayOfByte['ƕ'] = 56;
    arrayOfByte['Ɩ'] = -127;
    arrayOfByte['Ɨ'] = -18;
    arrayOfByte['Ƙ'] = 92;
    arrayOfByte['ƙ'] = 126;
    arrayOfByte['ƚ'] = 103;
    arrayOfByte['ƛ'] = -12;
    arrayOfByte['Ɯ'] = 2;
    arrayOfByte['Ɲ'] = 82;
    arrayOfByte['ƞ'] = -58;
    arrayOfByte['Ɵ'] = -41;
    arrayOfByte['Ơ'] = -58;
    arrayOfByte['ơ'] = -38;
    arrayOfByte['Ƣ'] = -63;
    arrayOfByte['ƣ'] = 117;
    arrayOfByte['Ƥ'] = -80;
    arrayOfByte['ƥ'] = -64;
    arrayOfByte['Ʀ'] = 103;
    arrayOfByte['Ƨ'] = -118;
    arrayOfByte['ƨ'] = -69;
    arrayOfByte['Ʃ'] = -91;
    arrayOfByte['ƪ'] = 109;
    arrayOfByte['ƫ'] = 30;
    arrayOfByte['Ƭ'] = 34;
    arrayOfByte['ƭ'] = 69;
    arrayOfByte['Ʈ'] = -15;
    arrayOfByte['Ư'] = -84;
    arrayOfByte['ư'] = 5;
    arrayOfByte['Ʊ'] = 88;
    arrayOfByte['Ʋ'] = 52;
    arrayOfByte['Ƴ'] = 73;
    arrayOfByte['ƴ'] = -12;
    arrayOfByte['Ƶ'] = -11;
    arrayOfByte['ƶ'] = -61;
    arrayOfByte['Ʒ'] = -28;
    arrayOfByte['Ƹ'] = -41;
    arrayOfByte['ƹ'] = 1;
    arrayOfByte['ƺ'] = -38;
    arrayOfByte['ƻ'] = 92;
    arrayOfByte['Ƽ'] = -104;
    arrayOfByte['ƽ'] = -57;
    arrayOfByte['ƾ'] = 99;
    arrayOfByte['ƿ'] = -70;
    arrayOfByte['ǀ'] = -32;
    arrayOfByte['ǁ'] = 122;
    arrayOfByte['ǂ'] = 15;
    arrayOfByte['ǃ'] = 22;
    arrayOfByte['Ǆ'] = 67;
    arrayOfByte['ǅ'] = 126;
    arrayOfByte['ǆ'] = -83;
    arrayOfByte['Ǉ'] = -123;
    arrayOfByte['ǈ'] = 37;
    arrayOfByte['ǉ'] = 9;
    arrayOfByte['Ǌ'] = 59;
    arrayOfByte['ǋ'] = 107;
    arrayOfByte['ǌ'] = 50;
    arrayOfByte['Ǎ'] = 26;
    arrayOfByte['ǎ'] = -26;
    arrayOfByte['Ǐ'] = -48;
    arrayOfByte['ǐ'] = -45;
    arrayOfByte['Ǒ'] = 116;
    arrayOfByte['ǒ'] = -56;
    arrayOfByte['Ǔ'] = 38;
    arrayOfByte['ǔ'] = 64;
    arrayOfByte['Ǖ'] = 20;
    arrayOfByte['ǖ'] = 4;
    arrayOfByte['Ǘ'] = 75;
    arrayOfByte['ǘ'] = 26;
    arrayOfByte['Ǚ'] = -113;
    arrayOfByte['ǚ'] = 117;
    arrayOfByte['Ǜ'] = 25;
    arrayOfByte['ǜ'] = -73;
    arrayOfByte['ǝ'] = 22;
    arrayOfByte['Ǟ'] = -47;
    arrayOfByte['ǟ'] = -102;
    arrayOfByte['Ǡ'] = 94;
    arrayOfByte['ǡ'] = 84;
    arrayOfByte['Ǣ'] = -120;
    arrayOfByte['ǣ'] = 53;
    arrayOfByte['Ǥ'] = 75;
    arrayOfByte['ǥ'] = 100;
    arrayOfByte['Ǧ'] = 106;
    arrayOfByte['ǧ'] = 93;
    arrayOfByte['Ǩ'] = -11;
    arrayOfByte['ǩ'] = 77;
    arrayOfByte['Ǫ'] = 40;
    arrayOfByte['ǫ'] = 88;
    arrayOfByte['Ǭ'] = 119;
    arrayOfByte['ǭ'] = 43;
    arrayOfByte['Ǯ'] = -23;
    arrayOfByte['ǯ'] = -123;
    arrayOfByte['ǰ'] = 11;
    arrayOfByte['Ǳ'] = 43;
    arrayOfByte['ǲ'] = 79;
    arrayOfByte['ǳ'] = 94;
    arrayOfByte['Ǵ'] = -77;
    arrayOfByte['ǵ'] = 98;
    arrayOfByte['Ƕ'] = 26;
    arrayOfByte['Ƿ'] = 32;
    arrayOfByte['Ǹ'] = 20;
    arrayOfByte['ǹ'] = -60;
    arrayOfByte['Ǻ'] = -77;
    arrayOfByte['ǻ'] = 23;
    arrayOfByte['Ǽ'] = -87;
    arrayOfByte['ǽ'] = 73;
    arrayOfByte['Ǿ'] = -22;
    arrayOfByte['ǿ'] = 62;
    arrayOfByte['Ȁ'] = 120;
    arrayOfByte['ȁ'] = -65;
    arrayOfByte['Ȃ'] = -95;
    arrayOfByte['ȃ'] = -113;
    arrayOfByte['Ȅ'] = 24;
    arrayOfByte['ȅ'] = 38;
    arrayOfByte['Ȇ'] = -21;
    arrayOfByte['ȇ'] = 5;
    arrayOfByte['Ȉ'] = -120;
    arrayOfByte['ȉ'] = -52;
    arrayOfByte['Ȋ'] = -38;
    arrayOfByte['ȋ'] = -96;
    arrayOfByte['Ȍ'] = 14;
    arrayOfByte['ȍ'] = 1;
    arrayOfByte['Ȏ'] = 111;
    arrayOfByte['ȏ'] = 119;
    arrayOfByte['Ȑ'] = 48;
    arrayOfByte['ȑ'] = -24;
    arrayOfByte['Ȓ'] = -80;
    arrayOfByte['ȓ'] = -116;
    arrayOfByte['Ȕ'] = -52;
    arrayOfByte['ȕ'] = -90;
    arrayOfByte['Ȗ'] = 36;
    arrayOfByte['ȗ'] = 16;
    arrayOfByte['Ș'] = -73;
    arrayOfByte['ș'] = -35;
    arrayOfByte['Ț'] = -7;
    arrayOfByte['ț'] = -37;
    arrayOfByte['Ȝ'] = Byte.MIN_VALUE;
    arrayOfByte['ȝ'] = 29;
    arrayOfByte['Ȟ'] = -116;
    arrayOfByte['ȟ'] = -108;
    arrayOfByte['Ƞ'] = 16;
    arrayOfByte['ȡ'] = -60;
    arrayOfByte['Ȣ'] = 65;
    arrayOfByte['ȣ'] = 36;
    arrayOfByte['Ȥ'] = -38;
    arrayOfByte['ȥ'] = -13;
    arrayOfByte['Ȧ'] = -92;
    arrayOfByte['ȧ'] = -99;
    arrayOfByte['Ȩ'] = -121;
    arrayOfByte['ȩ'] = -29;
    arrayOfByte['Ȫ'] = -101;
    arrayOfByte['ȫ'] = -96;
    arrayOfByte['Ȭ'] = -21;
    arrayOfByte['ȭ'] = 32;
    arrayOfByte['Ȯ'] = -54;
    arrayOfByte['ȯ'] = -4;
    arrayOfByte['Ȱ'] = -81;
    arrayOfByte['ȱ'] = 89;
    arrayOfByte['Ȳ'] = -50;
    arrayOfByte['ȳ'] = -85;
    arrayOfByte['ȴ'] = -14;
    arrayOfByte['ȵ'] = -77;
    arrayOfByte['ȶ'] = -93;
    arrayOfByte['ȷ'] = -99;
    arrayOfByte['ȸ'] = 95;
    arrayOfByte['ȹ'] = 32;
    arrayOfByte['Ⱥ'] = -10;
    arrayOfByte['Ȼ'] = -25;
    arrayOfByte['ȼ'] = -76;
    arrayOfByte['Ƚ'] = 55;
    arrayOfByte['Ⱦ'] = -93;
    arrayOfByte['ȿ'] = -101;
    arrayOfByte['ɀ'] = 120;
    arrayOfByte['Ɂ'] = 59;
    arrayOfByte['ɂ'] = -24;
    arrayOfByte['Ƀ'] = 98;
    arrayOfByte['Ʉ'] = -34;
    arrayOfByte['Ʌ'] = 71;
    arrayOfByte['Ɇ'] = 68;
    arrayOfByte['ɇ'] = -118;
    arrayOfByte['Ɉ'] = -51;
    arrayOfByte['ɉ'] = -80;
    arrayOfByte['Ɋ'] = -32;
    arrayOfByte['ɋ'] = -86;
    arrayOfByte['Ɍ'] = 55;
    arrayOfByte['ɍ'] = 20;
    arrayOfByte['Ɏ'] = 58;
    arrayOfByte['ɏ'] = -69;
    arrayOfByte['ɐ'] = 80;
    arrayOfByte['ɑ'] = 33;
    arrayOfByte['ɒ'] = 90;
    arrayOfByte['ɓ'] = 42;
    arrayOfByte['ɔ'] = -116;
    arrayOfByte['ɕ'] = -16;
    arrayOfByte['ɖ'] = 49;
    arrayOfByte['ɗ'] = 101;
    arrayOfByte['ɘ'] = -53;
    arrayOfByte['ə'] = 13;
    arrayOfByte['ɚ'] = -110;
    arrayOfByte['ɛ'] = 12;
    arrayOfByte['ɜ'] = -64;
    arrayOfByte['ɝ'] = -85;
    arrayOfByte['ɞ'] = -36;
    arrayOfByte['ɟ'] = -68;
    arrayOfByte['ɡ'] = -52;
    arrayOfByte['ɢ'] = -31;
    arrayOfByte['ɣ'] = -59;
    arrayOfByte['ɤ'] = 1;
    arrayOfByte['ɥ'] = -8;
    arrayOfByte['ɦ'] = -82;
    arrayOfByte['ɧ'] = 89;
    arrayOfByte['ɨ'] = -70;
    arrayOfByte['ɩ'] = 28;
    arrayOfByte['ɪ'] = 58;
    arrayOfByte['ɫ'] = 73;
    arrayOfByte['ɬ'] = -16;
    arrayOfByte['ɭ'] = 78;
    arrayOfByte['ɮ'] = -60;
    arrayOfByte['ɯ'] = 21;
    arrayOfByte['ɰ'] = 10;
    arrayOfByte['ɱ'] = -57;
    arrayOfByte['ɲ'] = -115;
    arrayOfByte['ɳ'] = -97;
    arrayOfByte['ɴ'] = -21;
    arrayOfByte['ɵ'] = -74;
    arrayOfByte['ɶ'] = 26;
    arrayOfByte['ɷ'] = 18;
    arrayOfByte['ɸ'] = -115;
    arrayOfByte['ɹ'] = -62;
    arrayOfByte['ɺ'] = -19;
    arrayOfByte['ɻ'] = -80;
    arrayOfByte['ɼ'] = 4;
    arrayOfByte['ɽ'] = -103;
    arrayOfByte['ɾ'] = -38;
    arrayOfByte['ɿ'] = -26;
    arrayOfByte['ʀ'] = 49;
    arrayOfByte['ʁ'] = 103;
    arrayOfByte['ʂ'] = -76;
    arrayOfByte['ʃ'] = 77;
    arrayOfByte['ʄ'] = 86;
    arrayOfByte['ʅ'] = 110;
    arrayOfByte['ʆ'] = 58;
    arrayOfByte['ʇ'] = -76;
    arrayOfByte['ʈ'] = -127;
    arrayOfByte['ʉ'] = -61;
    arrayOfByte['ʊ'] = -18;
    arrayOfByte['ʋ'] = -33;
    arrayOfByte['ʌ'] = 48;
    arrayOfByte['ʍ'] = 32;
    arrayOfByte['ʎ'] = 24;
    arrayOfByte['ʏ'] = -21;
    arrayOfByte['ʐ'] = -14;
    arrayOfByte['ʑ'] = 104;
    arrayOfByte['ʒ'] = 16;
    arrayOfByte['ʓ'] = -4;
    arrayOfByte['ʔ'] = -44;
    arrayOfByte['ʕ'] = 26;
    arrayOfByte['ʖ'] = 33;
    arrayOfByte['ʗ'] = -45;
    arrayOfByte['ʘ'] = -11;
    arrayOfByte['ʙ'] = 26;
    arrayOfByte['ʚ'] = 33;
    arrayOfByte['ʛ'] = -121;
    arrayOfByte['ʜ'] = 67;
    arrayOfByte['ʝ'] = -88;
    arrayOfByte['ʞ'] = -14;
    arrayOfByte['ʟ'] = 81;
    arrayOfByte['ʠ'] = 77;
    arrayOfByte['ʡ'] = 28;
    arrayOfByte['ʢ'] = -118;
    arrayOfByte['ʣ'] = -103;
    arrayOfByte['ʤ'] = 112;
    arrayOfByte['ʥ'] = -22;
    arrayOfByte['ʦ'] = 54;
    arrayOfByte['ʧ'] = 49;
    arrayOfByte['ʨ'] = 5;
    arrayOfByte['ʩ'] = 39;
    arrayOfByte['ʪ'] = -55;
    arrayOfByte['ʫ'] = 82;
    arrayOfByte['ʬ'] = -123;
    arrayOfByte['ʭ'] = -21;
    arrayOfByte['ʮ'] = 90;
    arrayOfByte['ʯ'] = 71;
    arrayOfByte['ʰ'] = -22;
    arrayOfByte['ʱ'] = 10;
    arrayOfByte['ʲ'] = -18;
    arrayOfByte['ʳ'] = -69;
    arrayOfByte['ʴ'] = 68;
    arrayOfByte['ʵ'] = 102;
    arrayOfByte['ʶ'] = -59;
    arrayOfByte['ʷ'] = -103;
    arrayOfByte['ʸ'] = 126;
    arrayOfByte['ʹ'] = 118;
    arrayOfByte['ʺ'] = 103;
    arrayOfByte['ʻ'] = -120;
    arrayOfByte['ʼ'] = Byte.MAX_VALUE;
    arrayOfByte['ʽ'] = 98;
    arrayOfByte['ʾ'] = -9;
    arrayOfByte['ʿ'] = 100;
    arrayOfByte['ˀ'] = 100;
    arrayOfByte['ˁ'] = -75;
    arrayOfByte['˂'] = -110;
    arrayOfByte['˃'] = -56;
    arrayOfByte['˄'] = 36;
    arrayOfByte['˅'] = 98;
    arrayOfByte['ˆ'] = 103;
    arrayOfByte['ˇ'] = 24;
    arrayOfByte['ˈ'] = -66;
    arrayOfByte['ˉ'] = -78;
    arrayOfByte['ˊ'] = 115;
    arrayOfByte['ˋ'] = -105;
    arrayOfByte['ˌ'] = 21;
    arrayOfByte['ˍ'] = 21;
    arrayOfByte['ˎ'] = 61;
    arrayOfByte['ˏ'] = 63;
    arrayOfByte['ː'] = 102;
    arrayOfByte['ˑ'] = 50;
    arrayOfByte['˒'] = 123;
    arrayOfByte['˓'] = 29;
    arrayOfByte['˔'] = 9;
    arrayOfByte['˕'] = -117;
    arrayOfByte['˖'] = -124;
    arrayOfByte['˗'] = -123;
    arrayOfByte['˘'] = -106;
    arrayOfByte['˙'] = 60;
    arrayOfByte['˚'] = 112;
    arrayOfByte['˛'] = 51;
    arrayOfByte['˜'] = 49;
    arrayOfByte['˝'] = -37;
    arrayOfByte['˞'] = 94;
    arrayOfByte['˟'] = 64;
    arrayOfByte['ˠ'] = 99;
    arrayOfByte['ˡ'] = -53;
    arrayOfByte['ˢ'] = 51;
    arrayOfByte['ˣ'] = 88;
    arrayOfByte['ˤ'] = 95;
    arrayOfByte['˥'] = 79;
    arrayOfByte['˦'] = 27;
    arrayOfByte['˧'] = -1;
    arrayOfByte['˨'] = -87;
    arrayOfByte['˩'] = 13;
    arrayOfByte['˪'] = 41;
    arrayOfByte['˫'] = 8;
    arrayOfByte['ˬ'] = 30;
    arrayOfByte['˭'] = -99;
    arrayOfByte['ˮ'] = -58;
    arrayOfByte['˯'] = 67;
    arrayOfByte['˰'] = -42;
    arrayOfByte['˱'] = -84;
    arrayOfByte['˲'] = -34;
    arrayOfByte['˳'] = -31;
    arrayOfByte['˴'] = 9;
    arrayOfByte['˵'] = 103;
    arrayOfByte['˶'] = -92;
    arrayOfByte['˷'] = -84;
    arrayOfByte['˸'] = 79;
    arrayOfByte['˹'] = -54;
    arrayOfByte['˺'] = -120;
    arrayOfByte['˻'] = -10;
    arrayOfByte['˼'] = -78;
    arrayOfByte['˽'] = -29;
    arrayOfByte['˾'] = 63;
    arrayOfByte['˿'] = -44;
    arrayOfByte['̀'] = 88;
    arrayOfByte['́'] = 5;
    arrayOfByte['̂'] = 77;
    arrayOfByte['̃'] = 75;
    arrayOfByte['̄'] = -125;
    arrayOfByte['̅'] = -37;
    arrayOfByte['̆'] = -9;
    arrayOfByte['̇'] = -127;
    arrayOfByte['̈'] = -112;
    arrayOfByte['̉'] = 41;
    arrayOfByte['̊'] = -28;
    arrayOfByte['̋'] = -35;
    arrayOfByte['̌'] = 41;
    arrayOfByte['̍'] = -63;
    arrayOfByte['̎'] = -46;
    arrayOfByte['̏'] = -6;
    arrayOfByte['̐'] = -107;
    arrayOfByte['̑'] = 64;
    arrayOfByte['̒'] = -80;
    arrayOfByte['̓'] = 44;
    arrayOfByte['̔'] = 103;
    arrayOfByte['̕'] = -60;
    arrayOfByte['̖'] = -103;
    arrayOfByte['̗'] = 45;
    arrayOfByte['̘'] = 4;
    arrayOfByte['̙'] = -54;
    arrayOfByte['̚'] = 108;
    arrayOfByte['̛'] = -44;
    arrayOfByte['̜'] = 90;
    arrayOfByte['̝'] = 58;
    arrayOfByte['̞'] = -78;
    arrayOfByte['̟'] = -33;
    arrayOfByte['̠'] = 100;
    arrayOfByte['̡'] = -68;
    arrayOfByte['̢'] = -48;
    arrayOfByte['̣'] = 28;
    arrayOfByte['̤'] = -65;
    arrayOfByte['̥'] = 72;
    arrayOfByte['̦'] = 69;
    arrayOfByte['̧'] = -24;
    arrayOfByte['̨'] = -106;
    arrayOfByte['̩'] = -25;
    arrayOfByte['̪'] = 57;
    arrayOfByte['̫'] = 74;
    arrayOfByte['̬'] = -36;
    arrayOfByte['̭'] = 26;
    arrayOfByte['̮'] = 113;
    arrayOfByte['̯'] = 18;
    arrayOfByte['̰'] = -12;
    arrayOfByte['̱'] = 94;
    arrayOfByte['̲'] = 101;
    arrayOfByte['̳'] = -23;
    arrayOfByte['̴'] = 34;
    arrayOfByte['̵'] = -29;
    arrayOfByte['̶'] = 110;
    arrayOfByte['̷'] = -66;
    arrayOfByte['̸'] = 71;
    arrayOfByte['̹'] = 125;
    arrayOfByte['̺'] = 12;
    arrayOfByte['̻'] = -42;
    arrayOfByte['̼'] = -122;
    arrayOfByte['̾'] = 103;
    arrayOfByte['̿'] = Byte.MIN_VALUE;
    arrayOfByte['̀'] = 17;
    arrayOfByte['́'] = -4;
    arrayOfByte['͂'] = -121;
    arrayOfByte['̓'] = 97;
    arrayOfByte['̈́'] = -63;
    arrayOfByte['ͅ'] = -35;
    arrayOfByte['͆'] = -14;
    arrayOfByte['͇'] = 42;
    arrayOfByte['͈'] = -70;
    arrayOfByte['͉'] = -65;
    arrayOfByte['͊'] = -72;
    arrayOfByte['͋'] = -63;
    arrayOfByte['͌'] = 110;
    arrayOfByte['͍'] = 41;
    arrayOfByte['͎'] = 57;
    arrayOfByte['͏'] = 126;
    arrayOfByte['͐'] = 75;
    arrayOfByte['͑'] = -98;
    arrayOfByte['͒'] = 10;
    arrayOfByte['͓'] = -49;
    arrayOfByte['͔'] = -76;
    arrayOfByte['͕'] = 36;
    arrayOfByte['͖'] = 1;
    arrayOfByte['͗'] = -13;
    arrayOfByte['͘'] = 117;
    arrayOfByte['͙'] = -90;
    arrayOfByte['͚'] = 116;
    arrayOfByte['͛'] = -30;
    arrayOfByte['͜'] = 74;
    arrayOfByte['͝'] = 75;
    arrayOfByte['͞'] = 43;
    arrayOfByte['͟'] = 25;
    arrayOfByte['͠'] = 38;
    arrayOfByte['͡'] = 119;
    arrayOfByte['͢'] = -90;
    arrayOfByte['ͣ'] = 87;
    arrayOfByte['ͤ'] = -26;
    arrayOfByte['ͥ'] = -29;
    arrayOfByte['ͦ'] = -68;
    arrayOfByte['ͧ'] = -60;
    arrayOfByte['ͨ'] = -73;
    arrayOfByte['ͩ'] = -44;
    arrayOfByte['ͪ'] = 102;
    arrayOfByte['ͫ'] = -118;
    arrayOfByte['ͬ'] = -33;
    arrayOfByte['ͭ'] = -23;
    arrayOfByte['ͮ'] = 83;
    arrayOfByte['ͯ'] = 110;
    arrayOfByte['Ͱ'] = -94;
    arrayOfByte['ͱ'] = -9;
    arrayOfByte['Ͳ'] = 92;
    arrayOfByte['ͳ'] = 43;
    arrayOfByte['ʹ'] = 69;
    arrayOfByte['͵'] = 73;
    arrayOfByte['Ͷ'] = -49;
    arrayOfByte['ͷ'] = -46;
    arrayOfByte['͸'] = -113;
    arrayOfByte['͹'] = -83;
    arrayOfByte['ͺ'] = -25;
    arrayOfByte['ͻ'] = 16;
    arrayOfByte['ͼ'] = -12;
    arrayOfByte['ͽ'] = -9;
    arrayOfByte[';'] = 1;
    arrayOfByte['Ϳ'] = 68;
    arrayOfByte['΀'] = 82;
    arrayOfByte['΁'] = 73;
    arrayOfByte['΂'] = -119;
    arrayOfByte['΃'] = 117;
    arrayOfByte['΄'] = -105;
    arrayOfByte['΅'] = -92;
    arrayOfByte['Ά'] = -69;
    arrayOfByte['·'] = -99;
    arrayOfByte['Έ'] = 2;
    arrayOfByte['Ή'] = 105;
    arrayOfByte['Ί'] = -72;
    arrayOfByte['΋'] = -38;
    arrayOfByte['Ό'] = 68;
    arrayOfByte['΍'] = 87;
    arrayOfByte['Ύ'] = 120;
    arrayOfByte['Ώ'] = 50;
    arrayOfByte['ΐ'] = 16;
    arrayOfByte['Α'] = -60;
    arrayOfByte['Β'] = 83;
    arrayOfByte['Γ'] = -69;
    arrayOfByte['Δ'] = -22;
    arrayOfByte['Ε'] = 60;
    arrayOfByte['Ζ'] = 86;
    arrayOfByte['Η'] = 79;
    arrayOfByte['Θ'] = -91;
    arrayOfByte['Ι'] = 43;
    arrayOfByte['Κ'] = 120;
    arrayOfByte['Λ'] = -104;
    arrayOfByte['Μ'] = 85;
    arrayOfByte['Ν'] = 48;
    arrayOfByte['Ξ'] = 80;
    arrayOfByte['Ο'] = -2;
    arrayOfByte['Π'] = 109;
    arrayOfByte['Ρ'] = 28;
    arrayOfByte['΢'] = -44;
    arrayOfByte['Σ'] = 49;
    arrayOfByte['Τ'] = 122;
    arrayOfByte['Υ'] = -100;
    arrayOfByte['Φ'] = -74;
    arrayOfByte['Χ'] = -116;
    arrayOfByte['Ψ'] = -49;
    arrayOfByte['Ω'] = -20;
    arrayOfByte['Ϊ'] = -124;
    arrayOfByte['Ϋ'] = -39;
    arrayOfByte['ά'] = 111;
    arrayOfByte['έ'] = 25;
    arrayOfByte['ή'] = 25;
    arrayOfByte['ί'] = -17;
    arrayOfByte['ΰ'] = 86;
    arrayOfByte['α'] = 96;
    arrayOfByte['β'] = 28;
    arrayOfByte['γ'] = 109;
    arrayOfByte['δ'] = -57;
    arrayOfByte['ε'] = 47;
    arrayOfByte['ζ'] = 71;
    arrayOfByte['η'] = 21;
    arrayOfByte['θ'] = 15;
    arrayOfByte['ι'] = -40;
    arrayOfByte['κ'] = -9;
    arrayOfByte['λ'] = -96;
    arrayOfByte['μ'] = 53;
    arrayOfByte['ν'] = -20;
    arrayOfByte['ξ'] = 73;
    arrayOfByte['ο'] = 36;
    arrayOfByte['π'] = 93;
    arrayOfByte['ρ'] = 124;
    arrayOfByte['ς'] = -3;
    arrayOfByte['σ'] = 54;
    arrayOfByte['τ'] = 35;
    arrayOfByte['υ'] = 125;
    arrayOfByte['φ'] = -98;
    arrayOfByte['χ'] = -8;
    arrayOfByte['ψ'] = -47;
    arrayOfByte['ω'] = 55;
    arrayOfByte['ϊ'] = -66;
    arrayOfByte['ϋ'] = -68;
    arrayOfByte['ό'] = -14;
    arrayOfByte['ύ'] = 13;
    arrayOfByte['ώ'] = -118;
    arrayOfByte['Ϗ'] = 64;
    arrayOfByte['ϐ'] = 78;
    arrayOfByte['ϑ'] = -10;
    arrayOfByte['ϒ'] = 97;
    arrayOfByte['ϓ'] = -51;
    arrayOfByte['ϔ'] = 25;
    arrayOfByte['ϕ'] = 89;
    arrayOfByte['ϖ'] = -49;
    arrayOfByte['ϗ'] = -85;
    arrayOfByte['Ϙ'] = 7;
    arrayOfByte['ϙ'] = 53;
    arrayOfByte['Ϛ'] = -24;
    arrayOfByte['ϛ'] = -125;
    arrayOfByte['Ϝ'] = -22;
    arrayOfByte['ϝ'] = -24;
    arrayOfByte['Ϟ'] = 77;
    arrayOfByte['ϟ'] = -111;
    arrayOfByte['Ϡ'] = 59;
    arrayOfByte['ϡ'] = -89;
    arrayOfByte['Ϣ'] = 3;
    arrayOfByte['ϣ'] = 5;
    arrayOfByte['Ϥ'] = 59;
    arrayOfByte['ϥ'] = -95;
    arrayOfByte['Ϧ'] = 80;
    arrayOfByte['ϧ'] = -66;
    arrayOfByte['Ϩ'] = 29;
    arrayOfByte['ϩ'] = 54;
    arrayOfByte['Ϫ'] = 24;
    arrayOfByte['ϫ'] = 28;
    arrayOfByte['Ϭ'] = -59;
    arrayOfByte['ϭ'] = -121;
    arrayOfByte['Ϯ'] = -2;
    arrayOfByte['ϯ'] = -109;
    arrayOfByte['ϰ'] = -118;
    arrayOfByte['ϱ'] = 125;
    arrayOfByte['ϲ'] = -72;
    arrayOfByte['ϳ'] = 52;
    arrayOfByte['ϴ'] = 35;
    arrayOfByte['ϵ'] = -103;
    arrayOfByte['϶'] = -76;
    arrayOfByte['Ϸ'] = -41;
    arrayOfByte['ϸ'] = 55;
    arrayOfByte['Ϲ'] = 108;
    arrayOfByte['Ϻ'] = 13;
    arrayOfByte['ϻ'] = 104;
    arrayOfByte['ϼ'] = -111;
    arrayOfByte['Ͻ'] = -68;
    arrayOfByte['Ͼ'] = -29;
    arrayOfByte['Ͽ'] = 67;
    arrayOfByte['Ѐ'] = -82;
    arrayOfByte['Ё'] = -117;
    arrayOfByte['Ђ'] = -20;
    arrayOfByte['Ѓ'] = -8;
    arrayOfByte['Є'] = -118;
    arrayOfByte['Ѕ'] = -11;
    arrayOfByte['І'] = 57;
    arrayOfByte['Ї'] = -104;
    arrayOfByte['Ј'] = 32;
    arrayOfByte['Љ'] = -16;
    arrayOfByte['Њ'] = 63;
    arrayOfByte['Ћ'] = 103;
    arrayOfByte['Ќ'] = 90;
    arrayOfByte['Ѝ'] = -84;
    arrayOfByte['Ў'] = -68;
    arrayOfByte['Џ'] = -26;
    arrayOfByte['А'] = 81;
    arrayOfByte['Б'] = 43;
    arrayOfByte['В'] = -93;
    arrayOfByte['Г'] = 71;
    arrayOfByte['Д'] = -106;
    arrayOfByte['Е'] = 121;
    arrayOfByte['Ж'] = -52;
    arrayOfByte['З'] = -99;
    arrayOfByte['И'] = 55;
    arrayOfByte['Й'] = 8;
    arrayOfByte['К'] = -86;
    arrayOfByte['Л'] = 8;
    arrayOfByte['М'] = 58;
    arrayOfByte['Н'] = -25;
    arrayOfByte['О'] = 53;
    arrayOfByte['П'] = -83;
    arrayOfByte['Р'] = 121;
    arrayOfByte['С'] = -2;
    arrayOfByte['Т'] = 123;
    arrayOfByte['У'] = 68;
    arrayOfByte['Ф'] = 55;
    arrayOfByte['Х'] = -125;
    arrayOfByte['Ц'] = 15;
    arrayOfByte['Ч'] = 43;
    arrayOfByte['Ш'] = -78;
    arrayOfByte['Щ'] = -10;
    arrayOfByte['Ъ'] = -110;
    arrayOfByte['Ы'] = 45;
    arrayOfByte['Ь'] = 47;
    arrayOfByte['Э'] = 87;
    arrayOfByte['Ю'] = -54;
    arrayOfByte['Я'] = -89;
    arrayOfByte['а'] = -124;
    arrayOfByte['б'] = 97;
    arrayOfByte['в'] = 81;
    arrayOfByte['г'] = 58;
    arrayOfByte['д'] = 3;
    arrayOfByte['е'] = -92;
    arrayOfByte['ж'] = -35;
    arrayOfByte['з'] = 36;
    arrayOfByte['и'] = -125;
    arrayOfByte['й'] = 66;
    arrayOfByte['к'] = -17;
    arrayOfByte['л'] = 69;
    arrayOfByte['м'] = -63;
    arrayOfByte['н'] = -60;
    arrayOfByte['о'] = -38;
    arrayOfByte['п'] = 24;
    arrayOfByte['р'] = 118;
    arrayOfByte['с'] = -14;
    arrayOfByte['т'] = 18;
    arrayOfByte['у'] = -4;
    arrayOfByte['ф'] = -104;
    arrayOfByte['х'] = 105;
    arrayOfByte['ц'] = -59;
    arrayOfByte['ч'] = -80;
    arrayOfByte['ш'] = -84;
    arrayOfByte['щ'] = 14;
    arrayOfByte['ъ'] = -111;
    arrayOfByte['ы'] = -86;
    arrayOfByte['ь'] = -75;
    arrayOfByte['э'] = 95;
    arrayOfByte['ю'] = -68;
    arrayOfByte['я'] = 55;
    arrayOfByte['ѐ'] = -90;
    arrayOfByte['ё'] = 61;
    arrayOfByte['ђ'] = 73;
    arrayOfByte['ѓ'] = 93;
    arrayOfByte['є'] = -3;
    arrayOfByte['ѕ'] = 102;
    arrayOfByte['і'] = -33;
    arrayOfByte['ї'] = -105;
    arrayOfByte['ј'] = 76;
    arrayOfByte['љ'] = -2;
    arrayOfByte['њ'] = -20;
    arrayOfByte['ћ'] = 76;
    arrayOfByte['ќ'] = -58;
    arrayOfByte['ѝ'] = 115;
    arrayOfByte['ў'] = 90;
    arrayOfByte['џ'] = -125;
    arrayOfByte['Ѡ'] = -4;
    arrayOfByte['ѡ'] = -100;
    arrayOfByte['Ѣ'] = -69;
    arrayOfByte['ѣ'] = -16;
    arrayOfByte['Ѥ'] = -85;
    arrayOfByte['ѥ'] = -63;
    arrayOfByte['Ѧ'] = 114;
    arrayOfByte['ѧ'] = 17;
    arrayOfByte['Ѩ'] = 43;
    arrayOfByte['ѩ'] = 107;
    arrayOfByte['Ѫ'] = 125;
    arrayOfByte['ѫ'] = -48;
    arrayOfByte['Ѭ'] = -81;
    arrayOfByte['ѭ'] = -107;
    arrayOfByte['Ѯ'] = -15;
    arrayOfByte['ѯ'] = 32;
    arrayOfByte['Ѱ'] = -20;
    arrayOfByte['ѱ'] = 27;
    arrayOfByte['Ѳ'] = 122;
    arrayOfByte['ѳ'] = 117;
    arrayOfByte['Ѵ'] = 68;
    arrayOfByte['ѵ'] = -46;
    arrayOfByte['Ѷ'] = 60;
    arrayOfByte['ѷ'] = 114;
    arrayOfByte['Ѹ'] = -77;
    arrayOfByte['ѹ'] = -117;
    arrayOfByte['Ѻ'] = 33;
    arrayOfByte['ѻ'] = -86;
    arrayOfByte['Ѽ'] = 39;
    arrayOfByte['ѽ'] = 40;
    arrayOfByte['Ѿ'] = 23;
    arrayOfByte['ѿ'] = 24;
    arrayOfByte['Ҁ'] = 75;
    arrayOfByte['ҁ'] = 126;
    arrayOfByte['҂'] = -89;
    arrayOfByte['҃'] = 97;
    arrayOfByte['҄'] = -57;
    arrayOfByte['҅'] = -10;
    arrayOfByte['҆'] = 26;
    arrayOfByte['҇'] = -91;
    arrayOfByte['҈'] = 122;
    arrayOfByte['҉'] = 43;
    arrayOfByte['Ҋ'] = -109;
    arrayOfByte['ҋ'] = -101;
    arrayOfByte['Ҍ'] = 19;
    arrayOfByte['ҍ'] = -127;
    arrayOfByte['Ҏ'] = 116;
    arrayOfByte['ҏ'] = 124;
    arrayOfByte['Ґ'] = -98;
    arrayOfByte['ґ'] = 36;
    arrayOfByte['Ғ'] = 80;
    arrayOfByte['ғ'] = -43;
    arrayOfByte['Ҕ'] = 74;
    arrayOfByte['ҕ'] = -9;
    arrayOfByte['Җ'] = 96;
    arrayOfByte['җ'] = 97;
    arrayOfByte['Ҙ'] = -102;
    arrayOfByte['ҙ'] = -101;
    arrayOfByte['Қ'] = -93;
    arrayOfByte['қ'] = 31;
    arrayOfByte['Ҝ'] = 77;
    arrayOfByte['ҝ'] = -70;
    arrayOfByte['Ҟ'] = 57;
    arrayOfByte['ҟ'] = 58;
    arrayOfByte['Ҡ'] = -102;
    arrayOfByte['ҡ'] = -27;
    arrayOfByte['Ң'] = -125;
    arrayOfByte['ң'] = -33;
    arrayOfByte['Ҥ'] = 63;
    arrayOfByte['ҥ'] = 57;
    arrayOfByte['Ҧ'] = 123;
    arrayOfByte['ҧ'] = -109;
    arrayOfByte['Ҩ'] = -30;
    arrayOfByte['ҩ'] = 95;
    arrayOfByte['Ҫ'] = -1;
    arrayOfByte['ҫ'] = 89;
    arrayOfByte['Ҭ'] = 68;
    arrayOfByte['ҭ'] = -15;
    arrayOfByte['Ү'] = 51;
    arrayOfByte['ү'] = 4;
    arrayOfByte['Ұ'] = 36;
    arrayOfByte['ұ'] = -64;
    arrayOfByte['Ҳ'] = 126;
    arrayOfByte['ҳ'] = 50;
    arrayOfByte['Ҵ'] = 4;
    arrayOfByte['ҵ'] = 50;
    arrayOfByte['Ҷ'] = 26;
    arrayOfByte['ҷ'] = -117;
    arrayOfByte['Ҹ'] = -58;
    arrayOfByte['ҹ'] = -21;
    arrayOfByte['Һ'] = 27;
    arrayOfByte['һ'] = -83;
    arrayOfByte['Ҽ'] = 123;
    arrayOfByte['ҽ'] = -118;
    arrayOfByte['Ҿ'] = -67;
    arrayOfByte['ҿ'] = 25;
    arrayOfByte['Ӏ'] = -46;
    arrayOfByte['Ӂ'] = 51;
    arrayOfByte['ӂ'] = 102;
    arrayOfByte['Ӄ'] = 11;
    arrayOfByte['ӄ'] = 25;
    arrayOfByte['Ӆ'] = 111;
    arrayOfByte['ӆ'] = -16;
    arrayOfByte['Ӈ'] = -50;
    arrayOfByte['ӈ'] = -110;
    arrayOfByte['Ӊ'] = -55;
    arrayOfByte['ӊ'] = 99;
    arrayOfByte['Ӌ'] = 75;
    arrayOfByte['ӌ'] = 116;
    arrayOfByte['Ӎ'] = 101;
    arrayOfByte['ӎ'] = -41;
    arrayOfByte['ӏ'] = 9;
    arrayOfByte['Ӑ'] = 38;
    arrayOfByte['ӑ'] = 21;
    arrayOfByte['Ӓ'] = 104;
    arrayOfByte['ӓ'] = 98;
    arrayOfByte['Ӕ'] = 113;
    arrayOfByte['ӕ'] = -42;
    arrayOfByte['Ӗ'] = 33;
    arrayOfByte['ӗ'] = -115;
    arrayOfByte['Ә'] = 91;
    arrayOfByte['ә'] = 76;
    arrayOfByte['Ӛ'] = -12;
    arrayOfByte['ӛ'] = -76;
    arrayOfByte['Ӝ'] = 13;
    arrayOfByte['ӝ'] = 92;
    arrayOfByte['Ӟ'] = 28;
    arrayOfByte['ӟ'] = 19;
    arrayOfByte['Ӡ'] = 59;
    arrayOfByte['ӡ'] = 7;
    arrayOfByte['Ӣ'] = 69;
    arrayOfByte['ӣ'] = -124;
    arrayOfByte['Ӥ'] = 5;
    arrayOfByte['ӥ'] = -67;
    arrayOfByte['Ӧ'] = 125;
    arrayOfByte['ӧ'] = 52;
    arrayOfByte['Ө'] = 7;
    arrayOfByte['ө'] = 73;
    arrayOfByte['Ӫ'] = 20;
    arrayOfByte['ӫ'] = -62;
    arrayOfByte['Ӭ'] = -1;
    arrayOfByte['ӭ'] = -122;
    arrayOfByte['Ӯ'] = 81;
    arrayOfByte['ӯ'] = -43;
    w = arrayOfByte;
  }
  
  public j()
  {
    super(b(), p());
  }
  
  private static String b()
  {
    if (v == null) {
      v = a.a(u);
    }
    return v;
  }
  
  private static String p()
  {
    if (x == null) {
      x = a.a(w);
    }
    return x;
  }
  
  public float a()
  {
    return this.s;
  }
  
  public void a(float paramFloat)
  {
    this.n = paramFloat;
    a(this.i, this.n);
  }
  
  public void a(float paramFloat1, float paramFloat2)
  {
    if (this.t) {
      this.o = paramFloat2;
    }
    for (this.p = paramFloat1;; this.p = paramFloat2)
    {
      paramFloat1 = this.o;
      paramFloat2 = this.p;
      a(this.j, new float[] { paramFloat1, paramFloat2 });
      return;
      this.o = paramFloat1;
    }
  }
  
  public void a(int paramInt1, int paramInt2)
  {
    super.a(paramInt1, paramInt2);
    c(paramInt1, paramInt2);
  }
  
  @SuppressLint({"WrongCall"})
  public void a(int paramInt1, int paramInt2, FloatBuffer paramFloatBuffer1, FloatBuffer paramFloatBuffer2, FloatBuffer paramFloatBuffer3)
  {
    this.h = paramFloatBuffer3;
    this.g = paramInt2;
    super.a(paramInt1, paramFloatBuffer1, paramFloatBuffer2);
  }
  
  public void a(boolean paramBoolean)
  {
    this.t = paramBoolean;
  }
  
  public void b(float paramFloat)
  {
    this.q = paramFloat;
    a(this.k, this.q);
  }
  
  public void c()
  {
    super.c();
    this.a = GLES20.glGetAttribLocation(o(), "inputTextureCoordinate2");
    this.b = GLES20.glGetUniformLocation(o(), "inputImageTexture2");
    GLES20.glEnableVertexAttribArray(this.a);
    this.i = GLES20.glGetUniformLocation(o(), "excludeCircleRadius");
    this.j = GLES20.glGetUniformLocation(o(), "excludeCirclePoint");
    this.k = GLES20.glGetUniformLocation(o(), "excludeBlurSize");
    this.l = GLES20.glGetUniformLocation(o(), "aspectRatio");
    this.m = GLES20.glGetUniformLocation(o(), "whiteGuideAlpha");
    a(this.n);
    a(this.o, this.p);
    b(this.q);
    c(this.r);
    d(this.s);
  }
  
  public void c(float paramFloat)
  {
    this.r = paramFloat;
    a(this.l, this.r);
  }
  
  public void c(int paramInt1, int paramInt2)
  {
    c(paramInt2 / paramInt1);
  }
  
  public void d(float paramFloat)
  {
    this.s = paramFloat;
    a(this.m, this.s);
  }
  
  public float e(float paramFloat)
  {
    float f = 0.0F;
    if (this.s > 0.0F)
    {
      this.s -= paramFloat;
      if (this.s < 0.0F) {
        this.s = 0.0F;
      }
      d(this.s);
      f = this.s;
    }
    return f;
  }
  
  public void i()
  {
    super.i();
  }
  
  protected void j()
  {
    GLES20.glEnableVertexAttribArray(this.a);
    GLES20.glActiveTexture(33987);
    GLES20.glBindTexture(3553, this.g);
    GLES20.glUniform1i(this.b, 3);
    this.h.position(0);
    GLES20.glVertexAttribPointer(this.a, 2, 5126, false, 0, this.h);
  }
}


/* Location:              /Users/amaurremi/uw/stringoid/static-dynamic-comparison/apps/retrica/com.venticake.retrica-21-dex2jar.jar!/com/venticake/retrica/engine/a/j.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */